# Generated by Django 3.0.5 on 2020-04-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200419_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfomodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='contact_pref',
            field=models.IntegerField(choices=[(1, '+91'), (2, '+92'), (3, '+93')], default=1),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='job',
            field=models.IntegerField(choices=[(1, 'Designer'), (2, 'Manager'), (3, 'Accounting')], default=1),
        ),
    ]
